### ISSUE TITLE
Object_List.Class Write 이슈

### ISSUE THREAD

**Issue by kjun25** [realtimetech-solution/kson#33]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -20 out of bounds for length 1024

Kson context.fromObject()를 통해서 Object의 List를 toKsonString() 으로 파일로 생성 후 
Object List 클래스로 Kson 파일을 읽을때 발생
`context.fromObject(WolorChamberlist().toKsonString());`
`public class ChamberList {
	private List<Chamber> chamberList;
}`
`ChamberList chamberList = ksonContext.toObject(ChamberList.class, jsonValue);`

> [{"armDelay":-1,"channel":"6","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC82L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/6/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC82L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC82L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC82L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC82L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR6"},{"armDelay":-1,"channel":"7","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC83L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/7/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC83L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC83L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC83L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC83L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR7"},{"armDelay":-1,"channel":"11","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMS9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/11/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMS9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMS9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMS9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMS9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR11"},{"armDelay":-1,"channel":"15","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNS9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/15/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNS9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNS9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNS9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNS9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR15"},{"armDelay":-1,"channel":"13","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMy9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/13/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMy9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMy9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMy9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMy9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR13"},{"armDelay":-1,"channel":"4","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC80L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/4/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC80L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC80L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC80L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC80L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR4"},{"armDelay":-1,"channel":"5","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC81L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/5/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC81L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC81L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC81L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC81L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR5"},{"armDelay":-1,"channel":"10","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMC9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/10/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMC9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMC9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMC9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMC9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR10"},{"armDelay":-1,"channel":"14","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNC9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/14/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNC9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNC9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNC9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNC9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR14"},{"armDelay":3,"channel":"1","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xL2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/1/high","frameDelay":3,"waferThreshold":3,"isExistRaw":true,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xL2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xL2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":3,"name":"chamberName00","gateROI":{"y1":726.0F,"x1":0.0F,"y2":1026.0F,"x2":165.0F},"isSelected":true,"waferROI":{"y1":722.0F,"x1":407.0F,"y2":1123.0F,"x2":1220.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xL2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xL2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR1"},{"armDelay":-1,"channel":"12","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMi9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/12/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMi9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMi9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMi9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xMi9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR12"},{"armDelay":2,"channel":"2","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8yL2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/2/high","frameDelay":2,"waferThreshold":2,"isExistRaw":true,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8yL2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8yL2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":2,"name":"chamberName00","gateROI":{"y1":625.0F,"x1":0.0F,"y2":1196.0F,"x2":378.0F},"isSelected":true,"waferROI":{"y1":661.0F,"x1":725.0F,"y2":1109.0F,"x2":1231.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8yL2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8yL2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR2"},{"armDelay":-1,"channel":"9","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC85L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/9/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC85L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC85L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC85L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC85L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR9"},{"armDelay":1,"channel":"3","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8zL2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/3/high","frameDelay":1,"waferThreshold":1,"isExistRaw":true,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8zL2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8zL2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":1,"name":"chamberName00","gateROI":{"y1":686.0F,"x1":0.0F,"y2":1073.0F,"x2":68.0F},"isSelected":true,"waferROI":{"y1":491.0F,"x1":559.0F,"y2":1149.0F,"x2":1264.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8zL2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8zL2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR3"},{"armDelay":-1,"channel":"16","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNi9oaWdolightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/16/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNi9oaWdolightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNi9oaWdodarkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNi9oaWdo","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC8xNi9oaWdodarkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR16"},{"armDelay":-1,"channel":"8","lightWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC84L2hpZ2g=lightWaferGroundTruthImg.raw","rtsp":"rtsp://192.168.110.18:554/8/high","frameDelay":-1,"waferThreshold":-1,"isExistRaw":false,"lightGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC84L2hpZ2g=lightGateGroundTruthImg.raw","darkWaferRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC84L2hpZ2g=darkWaferGroundTruthImg.raw","gateThreshold":-1,"name":"chamberName00","gateROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"isSelected":false,"waferROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"id":"cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC84L2hpZ2g=","chuckROI":{"y1":-1.0F,"x1":-1.0F,"y2":-1.0F,"x2":-1.0F},"darkGateRawImg":"C:\\Users\\kjYun\\Documents\\GitHub\\wolor\\resources\\images\\cnRzcDovLzE5Mi4xNjguMTEwLjE4OjU1NC84L2hpZ2g=darkGateGroundTruthImg.raw","cameraName":"NSEM40163AIR8"}]

**Comment by devjeonghwan** [comment]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -20 out of bounds for length 1024

밑에 StackTrace도 올려주세요.

**Comment by kjun25** [comment]
StackTrace 추가했어요

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index -20 out of bounds for length 1024
	at com.realtimetech.kson.util.string.StringWriter.write(StringWriter.java:63)
	at com.realtimetech.kson.util.string.StringWriter.write(StringWriter.java:52)
	at com.realtimetech.kson.writer.KsonWriter.writeString(KsonWriter.java:163)
	at com.realtimetech.kson.writer.KsonWriter.recursiveWrite(KsonWriter.java:111)
	at com.realtimetech.kson.writer.KsonWriter.recursiveWrite(KsonWriter.java:84)
	at com.realtimetech.kson.writer.KsonWriter.toString(KsonWriter.java:59)
	at com.realtimetech.kson.element.JsonObject.toString(JsonObject.java:16)
	at com.realtimetech.kson.element.JsonValue.toKsonString(JsonValue.java:14)
	at com.realtimetech.kson.element.JsonObject.toString(JsonObject.java:22)
	at com.realtimetech.kson.KsonContext$3.deserialize(KsonContext.java:127)
	at com.realtimetech.kson.KsonContext$3.deserialize(KsonContext.java:118)
	at com.realtimetech.kson.KsonContext.createAtToObject(KsonContext.java:582)
	at com.realtimetech.kson.KsonContext.addToObjectStack(KsonContext.java:515)
	at com.realtimetech.kson.KsonContext.toObject(KsonContext.java:436)
	at ksonTest.KSon.ReadJson(KSon.java:31)
	at ksonTest.ksonMain.main(ksonMain.java:11)

**Comment by devjeonghwan** [comment]
ksonTest 패키지랑 샘플 데이터를 하이웍스로 보내주시면 확인해보겠습니다, 비슷하게 Class 구성해서 해보니 문제 재현이 안됩니다.
